import type { AreaTag } from "@/types";

export const subjectKeywords: Record<AreaTag, string[]> = {
  math: [
    "matematic",
    "algebra",
    "geometr",
    "trigonom",
    "calcul",
    "estad",
    "probab",
  ],
  science: [
    "fisic",
    "quimic",
    "biolog",
    "ecolog",
    "laboratorio",
    "anatom",
    "salud",
  ],
  language: [
    "espanol",
    "literatura",
    "lectura",
    "redaccion",
    "comunicacion",
    "ingles",
    "writing",
  ],
  social: [
    "historia",
    "filosofia",
    "etica",
    "sociologia",
    "economia",
    "derecho",
    "civica",
    "geografia",
  ],
  tech: [
    "informatic",
    "program",
    "computa",
    "tic",
    "tecnologia",
    "robot",
    "sistemas",
    "basededatos",
    "base de datos",
    "redes",
  ],
  creative: [
    "arte",
    "diseno",
    "dibujo",
    "musica",
    "teatro",
    "fotografia",
    "audiovisual",
    "animacion",
    "arquitectura",
  ],
};
